server:
  port: 8098

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    username: admin
    password: admin
    url: jdbc:mysql://localhost:3306/easycoachdb

jwt:
  secret: 5uRf1B1Rd
  expire: 1440
