server:
  port: 8098

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    username: admin
    password: admin
    url: jdbc:mysql://192.168.0.25:3306/easycoachdb
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    host: smtp.gmail.com
    port: 587
    username: appeasycoach@gmail.com
    password: AppEasyCoach@1997
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: 5uRf1B1Rd
  expire: 1440